title: Researcher
url: "http://jinwanchishen.me"
# baseurl: "/"

# markdown: kramdown

tracking_id: UA-105397150-1

sass:
    style: compressed
    sass_dir: _sass

# repository: "saffahyjp/jinwanchishen.me"